{% set name = "llama-index-question-gen-openai" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_question_gen_openai-{{ version }}.tar.gz
    sha256: efd3b468232808e9d3474670aaeab00e41b90f75f52d0c9bfbf11207e0963d62
  # https://github.com/run-llama/llama_index/issues/10806
  - url: https://raw.githubusercontent.com/run-llama/llama_index/main/LICENSE
    sha256: 24f40b5190fdacabc24ddbb5f76364d15e4f030925220ea300d8a2dd4993c8cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - llama-index-core >=0.12.0,<0.13.0
    - llama-index-program-openai >=0.3.0,<0.4.0
    - llama-index-llms-openai >=0.3.0,<0.4.0

test:
  imports:
    - llama_index.question_gen.openai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://llamaindex.ai
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/question_gen/llama-index-question-gen-openai
  summary: llama-index question_gen openai integration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
